### ISSUE TITLE
Drop the dark-purple ticks, legend keys, etc.

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/INBOtheme#10]
I saw this in an email-communication of @florisvdh and as I agree with him an issue seems appropriate. These dark-purple ticks and other graph elements makes the plots more colorfull/crowded than necessary. 

I know _des goûts et des couleurs ..._, so feel free to ignore the comment when there are good reasons  to do otherwise. 

On theming in general, I was impressed by the style package provided by BBC https://github.com/bbc/bbplot

**Comment by ThierryO** [comment]
The theme was designed by the in-house graphics designer.
